### PR TITLE
Deploy

### PR DESCRIPTION
**Pull request by amantur**
Added trigger to call ortelius-charts workflow to reindex charts when changes are made to this repo.

### CODE REVIEW

**Comment by amantur** [comment]
@sbtaylor15  @bradmccoydev kindly have a look

**Review by benhpoh — APPROVED** [review]
@sbtaylor15  after the meeting, we've introduced the trigger workflow as a separate stage, which gives it enough of a delay that the ortelius-charts repo picks up the changes. it now works as it should!

**Comment by benhpoh** [comment]
image

**Review by bradmccoydev — APPROVED** [review]
LGTM

**Pull request merged**
